"""add_queued_jobs_table

Revision ID: 9a985310ce4e
Revises: 6688bdf12b34
Create Date: 2025-11-17 22:07:50.520325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a985310ce4e"
down_revision: Union[str, Sequence[str], None] = "6688bdf12b34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queued_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.String(length=12), nullable=False),
        sa.Column("queue_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Create indexes
    op.create_index(
        "idx_queued_jobs_status_queue",
        "queued_jobs",
        ["status", "queue_name"],
        unique=False,
    )
    op.create_index(
        "idx_queued_jobs_upload_id", "queued_jobs", ["upload_id"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_queued_jobs_upload_id", table_name="queued_jobs")
    op.drop_index("idx_queued_jobs_status_queue", table_name="queued_jobs")
    op.drop_table("queued_jobs")
    # ### end Alembic commands ###
