"""Canonical SCREAMING_SNAKE API / job error codes."""

from __future__ import annotations

from enum import Enum
from typing import Dict


class ErrorCode(str, Enum):
    # Auth
    AUTH_USERNAME_TAKEN = "AUTH_USERNAME_TAKEN"
    AUTH_EMAIL_TAKEN = "AUTH_EMAIL_TAKEN"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"

    # API keys
    API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND"
    API_KEY_FORBIDDEN = "API_KEY_FORBIDDEN"
    API_KEY_BAD_REQUEST = "API_KEY_BAD_REQUEST"

    # Video
    VIDEO_NOT_FOUND = "VIDEO_NOT_FOUND"
    VIDEO_FORBIDDEN = "VIDEO_FORBIDDEN"
    VIDEO_BAD_REQUEST = "VIDEO_BAD_REQUEST"
    VIDEO_TOO_LARGE = "VIDEO_TOO_LARGE"
    VIDEO_INVALID_FILE = "VIDEO_INVALID_FILE"

    # Upload
    UPLOAD_SESSION_NOT_FOUND = "UPLOAD_SESSION_NOT_FOUND"
    UPLOAD_SESSION_GONE = "UPLOAD_SESSION_GONE"
    UPLOAD_BAD_REQUEST = "UPLOAD_BAD_REQUEST"
    UPLOAD_TOO_LARGE = "UPLOAD_TOO_LARGE"
    UPLOAD_OBJECT_MISSING = "UPLOAD_OBJECT_MISSING"

    # Playback
    PLAYBACK_NOT_READY = "PLAYBACK_NOT_READY"
    PLAYBACK_FORBIDDEN = "PLAYBACK_FORBIDDEN"
    PLAYBACK_UNAUTHORIZED = "PLAYBACK_UNAUTHORIZED"
    PLAYBACK_NOT_FOUND = "PLAYBACK_NOT_FOUND"
    PLAYBACK_BAD_REQUEST = "PLAYBACK_BAD_REQUEST"

    # Live
    LIVE_DISABLED = "LIVE_DISABLED"
    LIVE_NOT_FOUND = "LIVE_NOT_FOUND"
    LIVE_FORBIDDEN = "LIVE_FORBIDDEN"
    LIVE_UNAUTHORIZED = "LIVE_UNAUTHORIZED"

    # Jobs
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_CONFLICT = "JOB_CONFLICT"
    JOB_BAD_REQUEST = "JOB_BAD_REQUEST"
    JOB_FAILED = "JOB_FAILED"

    # Playlists
    PLAYLIST_NOT_FOUND = "PLAYLIST_NOT_FOUND"
    PLAYLIST_FORBIDDEN = "PLAYLIST_FORBIDDEN"
    PLAYLIST_CONFLICT = "PLAYLIST_CONFLICT"
    PLAYLIST_BAD_REQUEST = "PLAYLIST_BAD_REQUEST"

    # Webhooks
    WEBHOOK_NOT_FOUND = "WEBHOOK_NOT_FOUND"

    # Search / moderation / captions
    SEARCH_BAD_REQUEST = "SEARCH_BAD_REQUEST"
    SEARCH_UNAVAILABLE = "SEARCH_UNAVAILABLE"
    MODERATION_CONFLICT = "MODERATION_CONFLICT"
    MODERATION_BAD_REQUEST = "MODERATION_BAD_REQUEST"
    MODERATION_FORBIDDEN = "MODERATION_FORBIDDEN"
    CAPTION_NOT_FOUND = "CAPTION_NOT_FOUND"
    CAPTION_FORBIDDEN = "CAPTION_FORBIDDEN"

    # Share links / progress
    SHARE_NOT_FOUND = "SHARE_NOT_FOUND"
    SHARE_EXPIRED = "SHARE_EXPIRED"
    SHARE_REVOKED = "SHARE_REVOKED"
    SHARE_VIEW_LIMIT = "SHARE_VIEW_LIMIT"
    SHARE_FORBIDDEN = "SHARE_FORBIDDEN"
    SHARE_BAD_REQUEST = "SHARE_BAD_REQUEST"
    PROGRESS_INVALID = "PROGRESS_INVALID"
    OEMBED_NOT_FOUND = "OEMBED_NOT_FOUND"
    OEMBED_BAD_REQUEST = "OEMBED_BAD_REQUEST"
    HIGHLIGHT_NOT_FOUND = "HIGHLIGHT_NOT_FOUND"
    HIGHLIGHT_BAD_REQUEST = "HIGHLIGHT_BAD_REQUEST"

    # Validation / rate limit
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_INVALID_ID = "VALIDATION_INVALID_ID"
    VALIDATION_BAD_REQUEST = "VALIDATION_BAD_REQUEST"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    # Internal
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INTERNAL_STORAGE_FAILURE = "INTERNAL_STORAGE_FAILURE"
    INTERNAL_QUEUE_FAILURE = "INTERNAL_QUEUE_FAILURE"


# Default HTTP status when AppError does not override.
ERROR_HTTP_STATUS: Dict[ErrorCode, int] = {
    ErrorCode.AUTH_USERNAME_TAKEN: 400,
    ErrorCode.AUTH_EMAIL_TAKEN: 400,
    ErrorCode.AUTH_INVALID_CREDENTIALS: 401,
    ErrorCode.AUTH_INVALID_TOKEN: 401,
    ErrorCode.AUTH_UNAUTHORIZED: 401,
    ErrorCode.API_KEY_NOT_FOUND: 404,
    ErrorCode.API_KEY_FORBIDDEN: 403,
    ErrorCode.API_KEY_BAD_REQUEST: 400,
    ErrorCode.VIDEO_NOT_FOUND: 404,
    ErrorCode.VIDEO_FORBIDDEN: 403,
    ErrorCode.VIDEO_BAD_REQUEST: 400,
    ErrorCode.VIDEO_TOO_LARGE: 413,
    ErrorCode.VIDEO_INVALID_FILE: 400,
    ErrorCode.UPLOAD_SESSION_NOT_FOUND: 404,
    ErrorCode.UPLOAD_SESSION_GONE: 410,
    ErrorCode.UPLOAD_BAD_REQUEST: 400,
    ErrorCode.UPLOAD_TOO_LARGE: 413,
    ErrorCode.UPLOAD_OBJECT_MISSING: 400,
    ErrorCode.PLAYBACK_NOT_READY: 409,
    ErrorCode.PLAYBACK_FORBIDDEN: 403,
    ErrorCode.PLAYBACK_UNAUTHORIZED: 401,
    ErrorCode.PLAYBACK_NOT_FOUND: 404,
    ErrorCode.PLAYBACK_BAD_REQUEST: 400,
    ErrorCode.LIVE_DISABLED: 403,
    ErrorCode.LIVE_NOT_FOUND: 404,
    ErrorCode.LIVE_FORBIDDEN: 403,
    ErrorCode.LIVE_UNAUTHORIZED: 401,
    ErrorCode.JOB_NOT_FOUND: 404,
    ErrorCode.JOB_CONFLICT: 409,
    ErrorCode.JOB_BAD_REQUEST: 400,
    ErrorCode.JOB_FAILED: 500,
    ErrorCode.PLAYLIST_NOT_FOUND: 404,
    ErrorCode.PLAYLIST_FORBIDDEN: 403,
    ErrorCode.PLAYLIST_CONFLICT: 409,
    ErrorCode.PLAYLIST_BAD_REQUEST: 400,
    ErrorCode.WEBHOOK_NOT_FOUND: 404,
    ErrorCode.SEARCH_BAD_REQUEST: 400,
    ErrorCode.SEARCH_UNAVAILABLE: 409,
    ErrorCode.MODERATION_CONFLICT: 409,
    ErrorCode.MODERATION_BAD_REQUEST: 400,
    ErrorCode.MODERATION_FORBIDDEN: 403,
    ErrorCode.CAPTION_NOT_FOUND: 404,
    ErrorCode.CAPTION_FORBIDDEN: 403,
    ErrorCode.SHARE_NOT_FOUND: 404,
    ErrorCode.SHARE_EXPIRED: 410,
    ErrorCode.SHARE_REVOKED: 410,
    ErrorCode.SHARE_VIEW_LIMIT: 410,
    ErrorCode.SHARE_FORBIDDEN: 403,
    ErrorCode.SHARE_BAD_REQUEST: 400,
    ErrorCode.PROGRESS_INVALID: 400,
    ErrorCode.OEMBED_NOT_FOUND: 404,
    ErrorCode.OEMBED_BAD_REQUEST: 400,
    ErrorCode.HIGHLIGHT_NOT_FOUND: 404,
    ErrorCode.HIGHLIGHT_BAD_REQUEST: 400,
    ErrorCode.VALIDATION_FAILED: 422,
    ErrorCode.VALIDATION_INVALID_ID: 400,
    ErrorCode.VALIDATION_BAD_REQUEST: 400,
    ErrorCode.RATE_LIMIT_EXCEEDED: 429,
    ErrorCode.INTERNAL_SERVER_ERROR: 500,
    ErrorCode.INTERNAL_STORAGE_FAILURE: 500,
    ErrorCode.INTERNAL_QUEUE_FAILURE: 500,
}


def http_status_for(code: ErrorCode, override: int | None = None) -> int:
    if override is not None:
        return override
    return ERROR_HTTP_STATUS.get(code, 500)
